import Head from "next/head";
import Link from "next/link";
import { Container, Typography, Box, Button } from "@mui/material";
// import Image from "next/image";
// import { Geist, Geist_Mono } from "next/font/google";
// import styles from "@/styles/Home.module.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export default function Home() {
  return (
    <>
      <Head>
        <title>S2MP Social Media Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "start", height: "100vh", }}>
        <Box sx={{marginTop: "20vh"}}>
          <Typography variant="h1">S2MP</Typography>
        </Box>
        <Box>
          <Typography variant="h2">Welcome to S2MP</Typography>
        </Box>
        <Box>
          <Typography variant="h2">
            Made with ❤️ by{" "}
            <Link href="https://github.com/su0x7cf" style={{ textDecoration: "none", color: "hsl(305, 43.80%, 41.20%)" }}>
              su0x7cf
            </Link>
          </Typography>
        </Box>
        <Box>
            <Button variant="text" href="/auth-signin" sx={{marginTop: "100px", fontSize: "30px", color: "hsl(0, 0.00%, 27.80%)"}}>Continue to S2MP</Button>
        </Box>
      </Container>
    </>
  );
}
